/*
 * Seed de CNAEs (grau de risco)
 * Gerado automaticamente a partir do arquivo:
 *   SST - Anexo XI - Grau de risco.xlsx (aba 'Original')
 */

import { PrismaClient } from '@prisma/client';
import dotenv from 'dotenv';

dotenv.config();

const prisma = new PrismaClient();

const CNAE_SEED = [
  {
    code: '4724-5/00',
    title: 'COMÉRCIO VAREJISTA DE HORTIFRUTIGRANJEIROS',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1531-9/02',
    title: 'ACABAMENTO DE CALÇADOS DE COURO SOB CONTRATO',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4722-9/01',
    title: 'COMÉRCIO VAREJISTA DE CARNES - AÇOUGUES',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '9609-2/07',
    title: 'ALOJAMENTO DE ANIMAIS DOMÉSTICOS',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '8011-1/02',
    title: 'SERVIÇOS DE ADESTRAMENTO DE CÃES DE GUARDA',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '5310-5/02',
    title: 'ATIVIDADES DE FRANQUEADAS DO CORREIO NACIONAL',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '7911-2/00',
    title: 'AGÊNCIAS DE VIAGENS',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '9603-3/04',
    title: 'SERVIÇOS DE FUNERÁRIAS',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '9609-2/02',
    title: 'AGÊNCIAS MATRIMONIAIS',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1412-6/02',
    title: 'CONFECÇÃO, SOB MEDIDA, DE PEÇAS DO VESTUÁRIO, EXCETO ROUPAS ÍNTIMAS',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '9529-1/99',
    title: 'REPARAÇÃO E MANUTENÇÃO DE OUTROS OBJETOS E EQUIPAMENTOS PESSOAIS E DOMÉSTICOS NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '9329-8/99',
    title: 'OUTRAS ATIVIDADES DE RECREAÇÃO E LAZER NÃO ESPECIFICADAS ANTERIORMENTE',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4785-7/01',
    title: 'COMÉRCIO VAREJISTA DE ANTIGUIDADES',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '0159-8/01',
    title: 'APICULTURA',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '6399-2/00',
    title: 'OUTRAS ATIVIDADES DE PRESTAÇÃO DE SERVIÇOS DE INFORMAÇÃO NÃO ESPECIFICADAS ANTERIORMENTE',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '2599-3/01',
    title: 'SERVIÇOS DE CONFECÇÃO DE ARMAÇÕES METÁLICAS PARA A CONSTRUÇÃO',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '3212-4/00',
    title: 'FABRICAÇÃO DE BIJUTERIAS E ARTEFATOS SEMELHANTES',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '2219-6/00',
    title: 'FABRICAÇÃO DE ARTEFATOS DE BORRACHA NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '2349-4/99',
    title: 'FABRICAÇÃO DE PRODUTOS CERÂMICOS NÃO REFRATÁRIOS NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 4,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '2330-3/99',
    title: 'FABRICAÇÃO DE OUTROS ARTEFATOS E PRODUTOS DE CONCRETO, CIMENTO, FIBROCIMENTO, GESSO E MATERIAIS SEMELHANTES',
    nrRisk: 4,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1629-3/02',
    title: 'FABRICAÇÃO DE ARTEFATOS DIVERSOS DE CORTIÇA, BAMBU, PALHA, VIME E OUTROS MATERIAIS TRANÇADOS, EXCETO MÓVEIS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1529-7/00',
    title: 'FABRICAÇÃO DE ARTEFATOS DE COURO NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '2330-3/99',
    title: 'FABRICAÇÃO DE OUTROS ARTEFATOS E PRODUTOS DE CONCRETO, CIMENTO, FIBROCIMENTO, GESSO E MATERIAIS SEMELHANTES',
    nrRisk: 4,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '2399-1/01',
    title: 'DECORAÇÃO, LAPIDAÇÃO, GRAVAÇÃO, VITRIFICAÇÃO E OUTROS TRABALHOS EM CERÂMICA, LOUÇA, VIDRO E CRISTAL',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1629-3/01',
    title: 'FABRICAÇÃO DE ARTEFATOS DIVERSOS DE MADEIRA, EXCETO MÓVEIS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '2391-5/03',
    title: 'APARELHAMENTO DE PLACAS E EXECUÇÃO DE TRABALHOS EM MÁRMORE, GRANITO, ARDÓSIA E OUTRAS PEDRAS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '2599-3/99',
    title: 'FABRICAÇÃO DE OUTROS PRODUTOS DE METAL NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '3211-6/02',
    title: 'FABRICAÇÃO DE ARTEFATOS DE JOALHERIA E OURIVESARIA',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '3299-0/99',
    title: 'FABRICAÇÃO DE PRODUTOS DIVERSOS NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1749-4/00',
    title: 'FABRICAÇÃO DE PRODUTOS DE PASTAS CELULÓSICAS, PAPEL, CARTOLINA, PAPEL-CARTÃO E PAPELÃO ONDULADO NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '2229-3/99',
    title: 'FABRICAÇÃO DE ARTEFATOS DE MATERIAL PLÁSTICO PARA OUTROS USOS NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '2319-2/00',
    title: 'FABRICAÇÃO DE ARTIGOS DE VIDRO',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1359-6/00',
    title: 'FABRICAÇÃO DE OUTROS PRODUTOS TÊXTEIS NÃO ESPECIFICADOS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '9609-2/99',
    title: 'OUTRAS ATIVIDADES DE SERVIÇOS PESSOAIS NÃO ESPECIFICADAS ANTERIORMENTE',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4330-4/05',
    title: 'APLICAÇÃO DE REVESTIMENTOS E DE RESINAS EM INTERIORES E EXTERIORES',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4721-1/04',
    title: 'COMÉRCIO VAREJISTA DE DOCES, BALAS, BOMBONS E SEMELHANTES',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '9609-2/08',
    title: 'HIGIENE E EMBELEZAMENTO DE ANIMAIS DOMÉSTICOS',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '9602-5/01',
    title: 'CABELEIREIROS, MANICURE E PEDICURE',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '5099-8/99',
    title: 'OUTROS TRANSPORTES AQUAVIÁRIOS NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4712-1/00',
    title: 'COMÉRCIO VAREJISTA DE MERCADORIAS EM GERAL, COM PREDOMINÂNCIA DE PRODUTOS ALIMENTÍCIOS - MINIMERCADOS, MERCEARIAS E ARMAZÉNS',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1031-7/00',
    title: 'FABRICANTE DE CONSERVAS DE FRUTAS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '5320-2/02',
    title: 'SERVIÇOS DE ENTREGA RÁPIDA',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '7319-0/99',
    title: 'OUTRAS ATIVIDADES DE PUBLICIDADE NÃO ESPECIFICADAS ANTERIORMENTE',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1092-9/00',
    title: 'FABRICAÇÃO DE BISCOITOS E BOLACHAS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4322-3/01',
    title: 'INSTALAÇÕES HIDRÁULICAS, SANITÁRIAS E DE GÁS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1414-2/00',
    title: 'FABRICAÇÃO DE ACESSÓRIOS DO VESTUÁRIO, EXCETO PARA SEGURANÇA E PROTEÇÃO',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1340-5/99',
    title: 'OUTROS SERVIÇOS DE ACABAMENTO EM FIOS, TECIDOS, ARTEFATOS TÊXTEIS E PEÇAS DO VESTUÁRIO',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4520-0/06',
    title: 'SERVIÇOS DE BORRACHARIA PARA VEÍCULOS AUTOMOTORES',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '2391-5/01',
    title: 'BRITAMENTO DE PEDRAS, EXCETO ASSOCIADO À EXTRAÇÃO',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '9602-5/01',
    title: 'CABELEIREIROS, MANICURE E PEDICURE',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4330-4/05',
    title: 'APLICAÇÃO DE REVESTIMENTOS E DE RESINAS EM INTERIORES E EXTERIORES',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4399-1/99',
    title: 'SERVIÇOS ESPECIALIZADOS PARA CONSTRUÇÃO NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4930-2/02',
    title: 'TRANSPORTE RODOVIÁRIO DE CARGA, EXCETO PRODUTOS PERIGOSOS E MUDANÇAS, INTERMUNICIPAL, INTERESTADUAL E INTERNACIONAL',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '9001-9/02',
    title: 'PRODUÇÃO MUSICAL',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4520-0/08',
    title: 'SERVIÇOS DE CAPOTARIA',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1622-6/99',
    title: 'FABRICAÇÃO DE OUTROS ARTIGOS DE CARPINTARIA PARA CONSTRUÇÃO',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4330-4/02',
    title: 'INSTALAÇÃO DE PORTAS, JANELAS, TETOS, DIVISÓRIAS E ARMÁRIOS EMBUTIDOS DE QUALQUER MATERIAL',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '5212-5/00',
    title: 'CARGA E DESCARGA',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '9609-2/99',
    title: 'OUTRAS ATIVIDADES DE SERVIÇOS PESSOAIS NÃO ESPECIFICADAS ANTERIORMENTE',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '3811-4/00',
    title: 'COLETA DE RESÍDUOS NÃO PERIGOSOS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4930-2/01',
    title: 'TRANSPORTE RODOVIÁRIO DE CARGA, EXCETO PRODUTOS PERIGOSOS E MUDANÇAS, MUNICIPAL',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4930-2/04',
    title: 'TRANSPORTE RODOVIÁRIO DE MUDANÇAS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '8299-7/99',
    title: 'OUTRAS ATIVIDADES DE SERVIÇOS PRESTADOS PRINCIPALMENTE ÀS EMPRESAS NÃO ESPECIFICADAS ANTERIORMENTE',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4399-1/99',
    title: 'SERVIÇOS ESPECIALIZADOS PARA CONSTRUÇÃO NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1414-2/00',
    title: 'FABRICAÇÃO DE ACESSÓRIOS DO VESTUÁRIO, EXCETO PARA SEGURANÇA E PROTEÇÃO',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '9529-1/02',
    title: 'CHAVEIROS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1093-7/01',
    title: 'FABRICAÇÃO DE PRODUTOS DERIVADOS DO CACAU E DE CHOCOLATES',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '5612-1/00',
    title: 'SERVIÇOS AMBULANTES DE ALIMENTAÇÃO',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '5620-1/02',
    title: 'SERVIÇOS DE ALIMENTAÇÃO PARA EVENTOS E RECEPÇÕES - BUFÊ',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1821-1/00',
    title: 'SERVIÇOS DE PRÉ-IMPRESSÃO',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '8291-1/00',
    title: 'ATIVIDADES DE COBRANÇAS E INFORMAÇÕES CADASTRAIS',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '3104-7/00',
    title: 'FABRICAÇÃO DE COLCHÕES',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '3811-4/00',
    title: 'COLETA DE RESÍDUOS NÃO PERIGOSOS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '9609-2/06',
    title: 'SERVIÇOS DE TATUAGEM E COLOCAÇÃO DE PIERCING',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4330-4/05',
    title: 'APLICAÇÃO DE REVESTIMENTOS E DE RESINAS EM INTERIORES E EXTERIORES',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4789-0/05',
    title: 'COMÉRCIO VAREJISTA DE PRODUTOS SANEANTES DOMISSANITÁRIOS',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4789-0/05',
    title: 'COMÉRCIO VAREJISTA DE PRODUTOS SANEANTES DOMISSANITÁRIOS',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4789-0/04',
    title: 'COMÉRCIO VAREJISTA DE ANIMAIS VIVOS E DE ARTIGOS E ALIMENTOS PARA ANIMAIS DE ESTIMAÇÃO',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4755-5/02',
    title: 'COMERCIO VAREJISTA DE ARTIGOS DE ARMARINHO',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4789-0/99',
    title: 'COMÉRCIO VAREJISTA DE OUTROS PRODUTOS NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4763-6/04',
    title: 'COMÉRCIO VAREJISTA DE ARTIGOS DE CAÇA, PESCA E CAMPING',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4755-5/03',
    title: 'COMERCIO VAREJISTA DE ARTIGOS DE CAMA, MESA E BANHO',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4754-7/02',
    title: 'COMÉRCIO VAREJISTA DE ARTIGOS DE COLCHOARIA',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4759-8/99',
    title: 'COMÉRCIO VAREJISTA DE OUTROS ARTIGOS DE USO PESSOAL E DOMÉSTICO NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4754-7/03',
    title: 'COMÉRCIO VAREJISTA DE ARTIGOS DE ILUMINAÇÃO',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4783-1/01',
    title: 'COMÉRCIO VAREJISTA DE ARTIGOS DE JOALHERIA',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4774-1/00',
    title: 'COMÉRCIO VAREJISTA DE ARTIGOS DE ÓPTICA',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4783-1/02',
    title: 'COMÉRCIO VAREJISTA DE ARTIGOS DE RELOJOARIA',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4759-8/01',
    title: 'COMÉRCIO VAREJISTA DE ARTIGOS DE TAPEÇARIA, CORTINAS E PERSIANAS',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4782-2/02',
    title: 'COMÉRCIO VAREJISTA DE ARTIGOS DE VIAGEM',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4781-4/00',
    title: 'COMÉRCIO VAREJISTA DE ARTIGOS DO VESTUÁRIO E ACESSÓRIOS',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4789-0/99',
    title: 'COMÉRCIO VAREJISTA DE OUTROS PRODUTOS NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4763-6/02',
    title: 'COMÉRCIO VAREJISTA DE ARTIGOS ESPORTIVOS',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4789-0/08',
    title: 'COMÉRCIO VAREJISTA DE ARTIGOS FOTOGRÁFICOS E PARA FILMAGEM',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4789-0/99',
    title: 'COMÉRCIO VAREJISTA DE OUTROS PRODUTOS NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4773-3/00',
    title: 'COMÉRCIO VAREJISTA DE ARTIGOS MÉDICOS E ORTOPÉDICOS',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4759-8/99',
    title: 'COMÉRCIO VAREJISTA DE OUTROS ARTIGOS DE USO PESSOAL E DOMÉSTICO NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4785-7/99',
    title: 'COMÉRCIO VAREJISTA DE OUTROS ARTIGOS USADOS',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4723-7/00',
    title: 'COMÉRCIO VAREJISTA DE BEBIDAS',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4763-6/03',
    title: 'COMÉRCIO VAREJISTA DE BICICLETAS E TRICICLOS; PEÇAS E ACESSÓRIOS',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4789-0/01',
    title: 'COMÉRCIO VAREJISTA DE SUVENIRES, BIJUTERIAS E ARTESANATOS',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4763-6/01',
    title: 'COMÉRCIO VAREJISTA DE BRINQUEDOS E ARTIGOS RECREATIVOS',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4744-0/04',
    title: 'COMÉRCIO VAREJISTA DE CAL, AREIA, PEDRA BRITADA, TIJOLOS E TELHAS',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4782-2/01',
    title: 'COMÉRCIO VAREJISTA DE CALÇADOS',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4789-0/99',
    title: 'COMÉRCIO VAREJISTA DE OUTROS PRODUTOS NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4729-6/99',
    title: 'COMÉRCIO VAREJISTA DE PRODUTOS ALIMENTÍCIOS EM GERAL OU ESPECIALIZADO EM PRODUTOS ALIMENTÍCIOS NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4772-5/00',
    title: 'COMÉRCIO VAREJISTA DE COSMÉTICOS, PRODUTOS DE PERFUMARIA E DE HIGIENE PESSOAL',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4762-8/00',
    title: 'COMÉRCIO VAREJISTA DE DISCOS, CDS, DVDS E FITAS',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4753-9/00',
    title: 'COMÉRCIO VAREJISTA ESPECIALIZADO DE ELETRODOMÉSTICOS E EQUIPAMENTOS DE ÁUDIO E VÍDEO',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4789-0/99',
    title: 'COMÉRCIO VAREJISTA DE OUTROS PRODUTOS NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4752-1/00',
    title: 'COMÉRCIO VAREJISTA ESPECIALIZADO DE EQUIPAMENTOS DE TELEFONIA E COMUNICAÇÃO',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4751-2/01',
    title: 'COMÉRCIO VAREJISTA ESPECIALIZADO DE EQUIPAMENTOS E SUPRIMENTOS DE INFORMÁTICA',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4789-0/07',
    title: 'COMÉRCIO VAREJISTA DE EQUIPAMENTOS PARA ESCRITÓRIO',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4744-0/01',
    title: 'COMÉRCIO VAREJISTA DE FERRAGENS E FERRAMENTAS',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4789-0/99',
    title: 'COMÉRCIO VAREJISTA DE OUTROS PRODUTOS NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4756-3/00',
    title: 'COMÉRCIO VAREJISTA ESPECIALIZADO DE INSTRUMENTOS MUSICAIS E ACESSÓRIOS',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4721-1/03',
    title: 'COMÉRCIO VAREJISTA DE LATICÍNIOS E FRIOS',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4732-6/00',
    title: 'COMÉRCIO VAREJISTA DE LUBRIFICANTES',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4744-0/02',
    title: 'COMÉRCIO VAREJISTA DE MADEIRA E ARTEFATOS',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4744-0/99',
    title: 'COMÉRCIO VAREJISTA DE MATERIAIS DE CONSTRUÇÃO EM GERAL',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4744-0/03',
    title: 'COMÉRCIO VAREJISTA DE MATERIAIS HIDRÁULICOS',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4742-3/00',
    title: 'COMÉRCIO VAREJISTA DE MATERIAL ELÉTRICO',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4713-0/02',
    title: 'LOJAS DE VARIEDADES, EXCETO LOJAS DE DEPARTAMENTOS OU MAGAZINES',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4789-0/99',
    title: 'COMÉRCIO VAREJISTA DE OUTROS PRODUTOS NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4754-7/01',
    title: 'COMÉRCIO VAREJISTA DE MÓVEIS',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4789-0/03',
    title: 'COMÉRCIO VAREJISTA DE OBJETOS DE ARTE',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4541-2/06',
    title: 'COMÉRCIO A VAREJO DE PEÇAS E ACESSÓRIOS NOVOS PARA MOTOCICLETAS E MOTONETAS',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4530-7/03',
    title: 'COMÉRCIO A VAREJO DE PEÇAS E ACESSÓRIOS NOVOS PARA VEÍCULOS AUTOMOTORES',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4757-1/00',
    title: 'COMÉRCIO VAREJISTA ESPECIALIZADO DE PEÇAS E ACESSÓRIOS PARA APARELHOS ELETROELETRÔNICOS PARA USO DOMÉSTICO, EXCETO INFORMÁTICA E COMUNICAÇÃO',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4541-2/07',
    title: 'COMÉRCIO A VAREJO DE PEÇAS E ACESSÓRIOS USADOS PARA MOTOCICLETAS E MOTONETAS',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4530-7/04',
    title: 'COMÉRCIO A VAREJO DE PEÇAS E ACESSÓRIOS USADOS PARA VEÍCULOS AUTOMOTORES',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4789-0/99',
    title: 'COMÉRCIO VAREJISTA DE OUTROS PRODUTOS NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4789-0/02',
    title: 'COMÉRCIO VAREJISTA DE PLANTAS E FLORES NATURAIS',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4530-7/05',
    title: 'COMÉRCIO A VAREJO DE PNEUMÁTICOS E CÂMARAS-DE-AR',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4772-5/00',
    title: 'COMÉRCIO VAREJISTA DE COSMÉTICOS, PRODUTOS DE PERFUMARIA E DE HIGIENE PESSOAL',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4789-0/05',
    title: 'COMÉRCIO VAREJISTA DE PRODUTOS SANEANTES DOMISSANITÁRIOS',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4721-1/02',
    title: 'PADARIA E CONFEITARIA COM PREDOMINÂNCIA DE REVENDA',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4729-6/01',
    title: 'TABACARIA',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4729-6/99',
    title: 'COMÉRCIO VAREJISTA DE PRODUTOS ALIMENTÍCIOS EM GERAL OU ESPECIALIZADO EM PRODUTOS ALIMENTÍCIOS NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4789-0/99',
    title: 'COMÉRCIO VAREJISTA DE OUTROS PRODUTOS NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4789-0/99',
    title: 'COMÉRCIO VAREJISTA DE OUTROS PRODUTOS NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4789-0/99',
    title: 'COMÉRCIO VAREJISTA DE OUTROS PRODUTOS NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4759-8/99',
    title: 'COMÉRCIO VAREJISTA DE OUTROS ARTIGOS DE USO PESSOAL E DOMÉSTICO NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4755-5/01',
    title: 'COMÉRCIO VAREJISTA DE TECIDOS',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4741-5/00',
    title: 'COMÉRCIO VAREJISTA DE TINTAS E MATERIAIS PARA PINTURA',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4759-8/99',
    title: 'COMÉRCIO VAREJISTA DE OUTROS ARTIGOS DE USO PESSOAL E DOMÉSTICO NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4743-1/00',
    title: 'COMÉRCIO VAREJISTA DE VIDROS',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1031-7/00',
    title: 'FABRICAÇÃO DE CONSERVAS DE FRUTAS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '3299-0/02',
    title: 'FABRICAÇÃO DE CANETAS, LÁPIS E OUTROS ARTIGOS PARA ESCRITÓRIO',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1091-1/02',
    title: 'FABRICAÇÃO DE PRODUTOS DE PADARIA E CONFEITARIA COM PREDOMINÂNCIA DE PRODUÇÃO PRÓPRIA.',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1412-6/01',
    title: 'CONFECÇÃO DE PEÇAS DE VESTUÁRIO, EXCETO ROUPAS ÍNTIMAS E AS CONFECCIONADAS SOB MEDIDA',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1412-6/02',
    title: 'CONFECÇÃO, SOB MEDIDA, DE PEÇAS DO VESTUÁRIO, EXCETO ROUPAS ÍNTIMAS',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '5620-1/04',
    title: 'FORNECIMENTO DE ALIMENTOS PREPARADOS PREPONDERANTEMENTE PARA CONSUMO DOMICILIAR',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '0159-8/02',
    title: 'CRIAÇÃO DE ANIMAIS DE ESTIMAÇÃO',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '0322-1/04',
    title: 'CRIAÇÃO DE PEIXES ORNAMENTAIS EM ÁGUA DOCE',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '0321-3/04',
    title: 'CRIAÇÃO DE PEIXES ORNAMENTAIS EM ÁGUA SALGADA E SALOBRA',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1422-3/00',
    title: 'FABRICAÇÃO DE ARTIGOS DO VESTUÁRIO, PRODUZIDOS EM MALHARIAS E TRICOTAGENS, EXCETO MEIAS',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '9609-2/08',
    title: 'HIGIENE E EMBELEZAMENTO DE ANIMAIS DOMÉSTICOS',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '8712-3/00',
    title: 'ATIVIDADES DE FORNECIMENTO DE INFRA-ESTRUTURA DE APOIO E ASSISTÊNCIA A PACIENTE NO DOMICÍLIO',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '3211-6/03',
    title: 'CUNHAGEM DE MOEDAS E MEDALHAS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1510-6/00',
    title: 'CURTIMENTO E OUTRAS PREPARAÇÕES DE COURO',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1340-5/99',
    title: 'OUTROS SERVIÇOS DE ACABAMENTO EM FIOS, TECIDOS, ARTEFATOS TÊXTEIS E PEÇAS DO VESTUÁRIO',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '9602-5/02',
    title: 'ATIVIDADES DE ESTÉTICA E OUTROS SERVIÇOS DE CUIDADOS COM A BELEZA',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '9700-5/00',
    title: 'SERVIÇOS DOMÉSTICOS',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '8219-9/99',
    title: 'PREPARAÇÃO DE DOCUMENTOS E SERVIÇOS ESPECIALIZADOS DE APOIO ADMINISTRATIVO NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '9001-9/06',
    title: 'ATIVIDADES DE SONORIZAÇÃO E DE ILUMINAÇÃO',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '3600-6/02',
    title: 'DISTRIBUIÇÃO DE ÁGUA POR CAMINHÕES',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '5620-1/04',
    title: 'FORNECIMENTO DE ALIMENTOS PREPARADOS PREPONDERANTEMENTE PARA CONSUMO DOMICILIAR',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '5912-0/01',
    title: 'SERVIÇOS DE DUBLAGEM',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '5812-3/01',
    title: 'EDITOR DE JORNAIS DIÁRIOS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '5812-3/02',
    title: 'EDITOR DE JORNAIS NÃO DIÁRIOS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '5819-1/00',
    title: 'EDIÇÃO DE CADASTROS, LISTAS E DE OUTROS PRODUTOS GRÁFICOS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '5811-5/00',
    title: 'EDIÇÃO DE LIVROS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '5813-1/00',
    title: 'EDIÇÃO DE REVISTAS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '5912-0/99',
    title: 'ATIVIDADES DE PÓS-PRODUÇÃO CINEMATOGRÁFICA, DE VÍDEOS E DE PROGRAMAS DE TELEVISÃO NÃO ESPECIFICADAS ANTERIORMENTE',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4520-0/03',
    title: 'SERVIÇOS DE MANUTENÇÃO E REPARAÇÃO ELÉTRICA DE VEÍCULOS AUTOMOTORES',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4321-5/00',
    title: 'INSTALAÇÃO E MANUTENÇÃO ELÉTRICA',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1822-9/01',
    title: 'SERVIÇOS DE ENCADERNAÇÃO E PLASTIFICAÇÃO',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4322-3/01',
    title: 'INSTALAÇÕES HIDRÁULICAS, SANITÁRIAS E DE GÁS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '9609-2/99',
    title: 'OUTRAS ATIVIDADES DE SERVIÇOS PESSOAIS NÃO ESPECIFICADAS ANTERIORMENTE',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '5320-2/01',
    title: 'SERVIÇOS DE MALOTE NÃO REALIZADOS PELO CORREIO NACIONAL',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '8292-0/00',
    title: 'ENVASAMENTO E EMPACOTAMENTO SOB CONTRATO',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1340-5/01',
    title: 'ESTAMPARIA E TEXTURIZAÇÃO EM FIOS, TECIDOS, ARTEFATOS TÊXTEIS E PEÇAS DO VESTUÁRIO',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '9609-2/08',
    title: 'HIGIENE E EMBELEZAMENTO DE ANIMAIS DOMÉSTICOS',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '9602-5/02',
    title: 'ATIVIDADES DE ESTÉTICA E OUTROS SERVIÇOS DE CUIDADOS COM A BELEZA',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '9529-1/05',
    title: 'REPARAÇÃO DE ARTIGOS DO MOBILIÁRIO',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1071-6/00',
    title: 'FABRICAÇÃO DE AÇÚCAR EM BRUTO',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1031-7/00',
    title: 'FABRICANTE DE CONSERVAS DE FRUTAS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1096-1/00',
    title: 'FABRICAÇÃO DE ALIMENTOS E PRATOS PRONTOS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1065-1/01',
    title: 'FABRICAÇÃO DE AMIDOS E FÉCULAS DE VEGETAIS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '2532-2/01',
    title: 'PRODUÇÃO DE ARTEFATOS ESTAMPADOS DE METAL',
    nrRisk: 4,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '2532-2/01',
    title: 'PRODUÇÃO DE ARTEFATOS ESTAMPADOS DE METAL',
    nrRisk: 4,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '3230-2/00',
    title: 'FABRICAÇÃO DE ARTEFATOS PARA PESCA E ESPORTE',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1351-1/00',
    title: 'FABRICAÇÃO DE ARTEFATOS TÊXTEIS PARA USO DOMÉSTICO',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '2541-1/00',
    title: 'FABRICAÇÃO DE ARTIGOS DE CUTELARIA',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '3299-0/05',
    title: 'FABRICAÇÃO DE AVIAMENTOS PARA COSTURA',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1093-7/02',
    title: 'FABRICAÇÃO DE FRUTAS CRISTALIZADAS, BALAS E SEMELHANTES',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1521-1/00',
    title: 'FABRICAÇÃO DE ARTIGOS PARA VIAGEM, BOLSAS E SEMELHANTES DE QUALQUER MATERIAL',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '3240-0/99',
    title: 'FABRICAÇÃO DE OUTROS BRINQUEDOS E JOGOS RECREATIVOS NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1539-4/00',
    title: 'FABRICAÇÃO DE CALÇADOS DE MATERIAIS NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1531-9/01',
    title: 'FABRICAÇÃO DE CALÇADOS DE COURO',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1099-6/05',
    title: 'FABRICAÇÃO DE PRODUTOS PARA INFUSÃO (CHÁ, MATE, ETC.)',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1414-2/00',
    title: 'FABRICAÇÃO DE ACESSÓRIOS DO VESTUÁRIO, EXCETO PARA SEGURANÇA E PROTEÇÃO',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1031-7/00',
    title: 'FABRICAÇÃO DE CONSERVAS DE FRUTAS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1032-5/99',
    title: 'FABRICAÇÃO DE CONSERVAS DE LEGUMES E OUTROS VEGETAIS, EXCETO PALMITO',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1732-0/00',
    title: 'FABRICAÇÃO DE EMBALAGENS DE CARTOLINA E PAPEL-CARTÃO',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1623-4/00',
    title: 'FABRICAÇÃO DE ARTEFATOS DE TANOARIA E DE EMBALAGENS DE MADEIRA',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1731-1/00',
    title: 'FABRICAÇÃO DE EMBALAGENS DE PAPEL',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1095-3/00',
    title: 'FABRICAÇÃO DE ESPECIARIAS, MOLHOS, TEMPEROS E CONDIMENTOS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '2512-8/00',
    title: 'FABRICAÇÃO DE ESQUADRIAS DE METAL',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1311-1/00',
    title: 'PREPARAÇÃO E FIAÇÃO DE FIBRAS DE ALGODÃO',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1312-0/00',
    title: 'PREPARAÇÃO E FIAÇÃO DE FIBRAS TÊXTEIS NATURAIS, EXCETO ALGODÃO',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1220-4/99',
    title: 'FABRICAÇÃO DE OUTROS PRODUTOS DO FUMO, EXCETO CIGARROS, CIGARRILHAS E CHARUTOS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1099-6/99',
    title: 'FABRICAÇÃO DE OUTROS PRODUTOS ALIMENTÍCIOS NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1099-6/04',
    title: 'FABRICAÇÃO DE GELO COMUM',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '3299-0/01',
    title: 'FABRICAÇÃO DE GUARDA-CHUVAS E SIMILARES',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1742-7/99',
    title: 'FABRICAÇÃO DE PRODUTOS DE PAPEL PARA USO DOMÉSTICO E HIGIÊNICO-SANITÁRIO NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '3220-5/00',
    title: 'FABRICAÇÃO DE INSTRUMENTOS MUSICAIS, PEÇAS E ACESSÓRIOS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '3240-0/99',
    title: 'FABRICAÇÃO DE OUTROS BRINQUEDOS E JOGOS RECREATIVOS NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1052-0/00',
    title: 'FABRICAÇÃO DE LATICÍNIOS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '3299-0/03',
    title: 'FABRICAÇÃO DE LETRAS, LETREIROS E PLACAS DE QUALQUER MATERIAL, EXCETO LUMINOSOS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '2740-6/02',
    title: 'FABRICAÇÃO DE LUMINÁRIAS E OUTROS EQUIPAMENTOS DE ILUMINAÇÃO',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1521-1/00',
    title: 'FABRICAÇÃO DE ARTIGOS PARA VIAGEM, BOLSAS E SEMELHANTES DE QUALQUER MATERIAL',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1094-5/00',
    title: 'FABRICAÇÃO DE MASSAS ALIMENTÍCIAS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1421-5/00',
    title: 'FABRICAÇÃO DE MEIAS',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1521-1/00',
    title: 'FABRICAÇÃO DE ARTIGOS PARA VIAGEM, BOLSAS E SEMELHANTES DE QUALQUER MATERIAL',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '3299-0/04',
    title: 'FABRICAÇÃO DE PAINÉIS E LETREIROS LUMINOSOS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1091-1/01',
    title: 'FABRICAÇÃO DE PRODUTOS DE PANIFICAÇÃO INDUSTRIAL',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1721-4/00',
    title: 'FABRICAÇÃO DE PAPEL',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1412-6/03',
    title: 'FACÇÃO DE PEÇAS DO VESTUÁRIO, EXCETO ROUPAS ÍNTIMAS',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1411-8/02',
    title: 'FACÇÃO DE ROUPAS ÍNTIMAS',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1413-4/03',
    title: 'FACÇÃO DE ROUPAS PROFISSIONAIS',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1540-8/00',
    title: 'FABRICAÇÃO DE PARTES PARA CALÇADOS, DE QUALQUER MATERIAL',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1031-7/00',
    title: 'FABRICAÇÃO DE CONSERVAS DE FRUTAS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1099-6/99',
    title: 'FABRICAÇÃO DE OUTROS PRODUTOS ALIMENTÍCIOS NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '3292-2/02',
    title: 'FABRICAÇÃO DE EQUIPAMENTOS E ACESSÓRIOS PARA SEGURANÇA PESSOAL E PROFISSIONAL',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1013-9/01',
    title: 'FABRICAÇÃO DE PRODUTOS DE CARNE',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1061-9/02',
    title: 'FABRICAÇÃO DE PRODUTOS DO ARROZ',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1071-6/00',
    title: 'FABRICAÇÃO DE AÇÚCAR EM BRUTO',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1122-4/03',
    title: 'FABRICAÇÃO DE REFRESCOS, XAROPES E PÓS PARA REFRESCOS, EXCETO REFRESCOS DE FRUTAS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1411-8/01',
    title: 'CONFECÇÃO DE ROUPAS ÍNTIMAS',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1033-3/01',
    title: 'FABRICAÇÃO DE SUCOS CONCENTRADOS DE FRUTAS, HORTALIÇAS E LEGUMES',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1033-3/02',
    title: 'FABRICAÇÃO DE SUCOS DE FRUTAS, HORTALIÇAS E LEGUMES, EXCETO CONCENTRADOS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '3299-0/06',
    title: 'FABRICAÇÃO DE VELAS, INCLUSIVE DECORATIVAS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1063-5/00',
    title: 'FABRICAÇÃO DE FARINHA DE MANDIOCA E DERIVADOS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1064-3/00',
    title: 'FABRICAÇÃO DE FARINHA DE MILHO E DERIVADOS, EXCETO ÓLEOS DE MILHO',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '2543-8/00',
    title: 'FABRICAÇÃO DE FERRAMENTAS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '2543-8/00',
    title: 'FABRICAÇÃO DE FERRAMENTAS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '7420-0/04',
    title: 'FILMAGEM DE FESTAS E EVENTOS',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '5620-1/01',
    title: 'FORNECIMENTO DE ALIMENTOS PREPARADOS PREPONDERANTEMENTE PARA EMPRESAS',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '3702-9/00',
    title: 'ATIVIDADES RELACIONADAS A ESGOTO, EXCETO A GESTÃO DE REDES',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '8219-9/01',
    title: 'FOTOCÓPIAS',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '7420-0/01',
    title: 'ATIVIDADES DE PRODUÇÃO DE FOTOGRAFIAS, EXCETO AÉREA E SUBMARINA',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '7420-0/02',
    title: 'ATIVIDADES DE PRODUÇÃO DE FOTOGRAFIAS AÉREAS E SUBMARINAS',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '7420-0/02',
    title: 'ATIVIDADES DE PRODUÇÃO DE FOTOGRAFIAS AÉREAS E SUBMARINAS',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4520-0/02',
    title: 'SERVIÇOS DE LANTERNAGEM OU FUNILARIA E PINTURA DE VEÍCULOS AUTOMOTORES',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '2539-0/02',
    title: 'SERVIÇOS DE TRATAMENTO E REVESTIMENTO EM METAIS',
    nrRisk: 4,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4330-4/03',
    title: 'OBRAS DE ACABAMENTO EM GESSO E ESTUQUE',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '8299-7/03',
    title: 'SERVIÇOS DE GRAVAÇÃO DE CARIMBOS, EXCETO CONFECÇÃO',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '5211-7/02',
    title: 'GUARDA-MÓVEIS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '7912-1/00',
    title: 'OPERADORES TURÍSTICOS',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '5229-0/02',
    title: 'SERVIÇOS DE REBOQUE DE VEÍCULOS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '9001-9/01',
    title: 'PRODUÇÃO TEATRAL',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4321-5/00',
    title: 'INSTALAÇÃO E MANUTENÇÃO ELÉTRICA',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4321-5/00',
    title: 'INSTALAÇÃO E MANUTENÇÃO ELÉTRICA',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4329-1/02',
    title: 'INSTALAÇÃO DE EQUIPAMENTOS PARA ORIENTAÇÃO À NAVEGAÇÃO MARÍTIMA, FLUVIAL E LACUSTRE',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4329-1/05',
    title: 'TRATAMENTOS TÉRMICOS, ACÚSTICOS OU DE VIBRAÇÃO',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4329-1/05',
    title: 'TRATAMENTOS TÉRMICOS, ACÚSTICOS OU DE VIBRAÇÃO',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '3321-0/00',
    title: 'INSTALAÇÃO DE MÁQUINAS E EQUIPAMENTOS INDUSTRIAIS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4329-1/01',
    title: 'INSTALAÇÃO DE PAINÉIS PUBLICITÁRIOS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '6190-6/99',
    title: 'OUTRAS ATIVIDADES DE TELECOMUNICAÇÕES NÃO ESPECIFICADAS ANTERIORMENTE',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4322-3/03',
    title: 'INSTALAÇÕES DE SISTEMA DE PREVENÇÃO CONTRA INCÊNDIO',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4520-0/07',
    title: 'SERVIÇOS DE INSTALAÇÃO, MANUTENÇÃO E REPARAÇÃO DE ACESSÓRIOS PARA VEÍCULOS AUTOMOTORES',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4329-1/03',
    title: 'INSTALAÇÃO, MANUTENÇÃO E REPARAÇÃO DE ELEVADORES, ESCADAS E ESTEIRAS ROLANTES',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '8020-0/02',
    title: 'OUTRAS ATIVIDADES DE SERVIÇOS DE SEGURANÇA',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4322-3/02',
    title: 'INSTALAÇÃO E MANUTENÇÃO DE SISTEMAS CENTRAIS DE AR CONDICIONADO, DE VENTILAÇÃO E REFRIGERAÇÃO',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '8592-9/99',
    title: 'ENSINO DE ARTE E CULTURA NÃO ESPECIFICADO ANTERIORMENTE',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '8592-9/02',
    title: 'ENSINO DE ARTES CÊNICAS, EXCETO DANÇA',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '8599-6/04',
    title: 'TREINAMENTO EM DESENVOLVIMENTO PROFISSIONAL E GERENCIAL',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '8599-6/05',
    title: 'CURSOS PREPARATÓRIOS PARA CONCURSOS',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '8593-7/00',
    title: 'ENSINO DE IDIOMAS',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '8599-6/03',
    title: 'TREINAMENTO EM INFORMÁTICA',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '8592-9/03',
    title: 'ENSINO DE MÚSICA',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '8130-3/00',
    title: 'ATIVIDADES PAISAGÍSTICAS',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4761-0/02',
    title: 'COMÉRCIO VAREJISTA DE JORNAIS E REVISTAS',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '3211-6/01',
    title: 'LAPIDAÇÃO DE GEMAS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '9601-7/01',
    title: 'LAVANDERIAS',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '9601-7/03',
    title: 'TOALHEIROS',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4520-0/05',
    title: 'SERVIÇOS DE LAVAGEM, LUBRIFICAÇÃO E POLIMENTO DE VEÍCULOS AUTOMOTORES',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '9609-2/99',
    title: 'OUTRAS ATIVIDADES DE SERVIÇOS PESSOAIS NÃO ESPECIFICADAS ANTERIORMENTE',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4761-0/01',
    title: 'COMÉRCIO VAREJISTA DE LIVROS',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '7732-2/02',
    title: 'ALUGUEL DE ANDAIMES',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '7729-2/01',
    title: 'ALUGUEL DE APARELHOS DE JOGOS ELETRÔNICOS',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '7721-7/00',
    title: 'ALUGUEL DE EQUIPAMENTOS RECREATIVOS E ESPORTIVOS',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '7739-0/02',
    title: 'ALUGUEL DE EQUIPAMENTOS CIENTÍFICOS, MÉDICOS E HOSPITALARES, SEM OPERADOR',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '7721-7/00',
    title: 'ALUGUEL DE EQUIPAMENTOS RECREATIVOS E ESPORTIVOS',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '7722-5/00',
    title: 'ALUGUEL DE FITAS DE VÍDEO, DVDS E SIMILARES',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '7729-2/99',
    title: 'ALUGUEL DE OUTROS OBJETOS PESSOAIS E DOMÉSTICOS NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '7731-4/00',
    title: 'ALUGUEL DE MÁQUINAS E EQUIPAMENTOS AGRÍCOLAS SEM OPERADOR',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '7732-2/01',
    title: 'ALUGUEL DE MÁQUINAS E EQUIPAMENTOS PARA CONSTRUÇÃO SEM OPERADOR, EXCETO ANDAIMES',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '7733-1/00',
    title: 'ALUGUEL DE MÁQUINAS E EQUIPAMENTOS PARA ESCRITÓRIO',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '7721-7/00',
    title: 'ALUGUEL DE EQUIPAMENTOS RECREATIVOS E ESPORTIVOS',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '7729-2/03',
    title: 'ALUGUEL DE MATERIAL MÉDICO',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '7719-5/99',
    title: 'LOCAÇÃO DE OUTROS MEIOS DE TRANSPORTE NÃO ESPECIFICADOS ANTERIORMENTE, SEM CONDUTOR',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '7729-2/02',
    title: 'ALUGUEL DE MÓVEIS, UTENSÍLIOS E APARELHOS DE USO DOMÉSTICO E PESSOAL; INSTRUMENTOS MUSICAIS',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '7729-2/02',
    title: 'ALUGUEL DE MÓVEIS, UTENSÍLIOS E APARELHOS DE USO DOMÉSTICO E PESSOAL; INSTRUMENTOS MUSICAIS',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '7723-3/00',
    title: 'ALUGUEL DE OBJETOS DO VESTUÁRIO, JÓIAS E ACESSÓRIOS',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '7739-0/99',
    title: 'ALUGUEL DE OUTRAS MÁQUINAS E EQUIPAMENTOS COMERCIAIS E INDUSTRIAIS NÃO ESPECIFICADOS ANTERIORMENTE, SEM OPERADOR',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '7739-0/03',
    title: 'ALUGUEL DE PALCOS, COBERTURAS E OUTRAS ESTRUTURAS DE USO TEMPORÁRIO, EXCETO ANDAIMES',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '7722-5/00',
    title: 'ALUGUEL DE FITAS DE VIDEO, DVDS E SIMILARES',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '9609-2/99',
    title: 'OUTRAS ATIVIDADES DE SERVIÇOS PESSOAIS NÃO ESPECIFICADAS ANTERIORMENTE',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '9329-8/99',
    title: 'OUTRAS ATIVIDADES DE RECREAÇÃO E LAZER NÃO ESPECIFICADAS ANTERIORMENTE',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '9602-5/01',
    title: 'CABELEIREIROS, MANICURE E PEDICURE',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '9602-5/02',
    title: 'ATIVIDADES DE ESTÉTICA E OUTROS SERVIÇOS DE CUIDADOS COM A BELEZA',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '3101-2/00',
    title: 'FABRICAÇÃO DE MÓVEIS COM PREDOMINÂNCIA DE MADEIRA',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '5620-1/04',
    title: 'FORNECIMENTO DE ALIMENTOS PREPARADOS PREPONDERANTEMENTE PARA CONSUMO DOMICILIAR',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4543-9/00',
    title: 'MANUTENÇÃO E REPARAÇÃO DE MOTOCICLETAS E MOTONETAS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4520-0/01',
    title: 'SERVIÇOS DE MANUTENÇÃO E REPARAÇÃO MECÂNICA DE VEÍCULOS AUTOMOTORES',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4712-1/00',
    title: 'COMÉRCIO VAREJISTA DE MERCADORIAS EM GERAL, COM PREDOMINÂNCIA DE PRODUTOS ALIMENTÍCIOS - MINIMERCADOS, MERCEARIAS E ARMAZÉNS',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '7490-1/02',
    title: 'ESCAFANDRIA E MERGULHO',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1069-4/00',
    title: 'MOAGEM E FABRICAÇÃO DE PRODUTOS DE ORIGEM VEGETAL NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '3329-5/01',
    title: 'SERVIÇOS DE MONTAGEM DE MÓVEIS DE QUALQUER MATERIAL',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4329-1/04',
    title: 'MONTAGEM E INSTALAÇÃO DE SISTEMAS E EQUIPAMENTOS DE ILUMINAÇÃO E SINALIZAÇÃO EM VIAS PÚBLICAS, PORTOS E AEROPORTOS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '5320-2/02',
    title: 'SERVIÇOS DE ENTREGA RÁPIDA',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '5229-0/99',
    title: 'OUTRAS ATIVIDADES AUXILIARES DOS TRANSPORTES TERRESTRES NÃO ESPECIFICADAS ANTERIORMENTE',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4923-0/01',
    title: 'SERVIÇO DE TÁXI',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '3103-9/00',
    title: 'FABRICAÇÃO DE MÓVEIS DE OUTROS MATERIAIS, EXCETO MADEIRA E METAL',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '3102-1/00',
    title: 'FABRICAÇÃO DE MÓVEIS COM PREDOMINÂNCIA DE METAL',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '2342-7/02',
    title: 'FABRICAÇÃO DE ARTEFATOS DE CERÂMICA E BARRO COZIDO PARA USO NA CONSTRUÇÃO, EXCETO AZULEJOS E PISOS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4929-9/03',
    title: 'ORGANIZAÇÃO DE EXCURSÕES EM VEÍCULOS RODOVIÁRIOS PRÓPRIOS, MUNICIPAL',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '9529-1/06',
    title: 'REPARAÇÃO DE JÓIAS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1091-1/01',
    title: 'FABRICAÇÃO DE PRODUTOS DE PANIFICAÇÃO',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '7319-0/02',
    title: 'PROMOÇÃO DE VENDAS',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4761-0/03',
    title: 'COMÉRCIO VAREJISTA DE ARTIGOS DE PAPELARIA',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4330-4/05',
    title: 'APLICAÇÃO DE REVESTIMENTOS E DE RESINAS EM INTERIORES E EXTERIORES',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4399-1/03',
    title: 'OBRAS DE ALVENARIA',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4722-9/02',
    title: 'PEIXARIA',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4520-0/02',
    title: 'SERVIÇOS DE LANTERNAGEM OU FUNILARIA E PINTURA DE VEÍCULOS AUTOMOTORES',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4330-4/04',
    title: 'SERVIÇOS DE PINTURA DE EDIFÍCIOS EM GERAL',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '5612-1/00',
    title: 'SERVIÇOS AMBULANTES DE ALIMENTAÇÃO',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '8129-0/00',
    title: 'ATIVIDADES DE LIMPEZA NÃO ESPECIFICADAS ANTERIORMENTE',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '5620-1/02',
    title: 'SERVIÇOS DE ALIMENTAÇÃO PARA EVENTOS E RECEPÇÕES - BUFÊ',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4399-1/05',
    title: 'PERFURAÇÃO E CONSTRUÇÃO DE POÇOS DE ÁGUA',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '0161-0/03',
    title: 'SERVIÇO DE PREPARAÇÃO DE TERRENO, CULTIVO E COLHEITA',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '0161-0/02',
    title: 'SERVIÇO DE PODA DE ARVORES PARA LAVOURA',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '0161-0/03',
    title: 'SERVIÇO DE PREPARAÇÃO DE TERRENO, CULTIVO E COLHEITA',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '0161-0/03',
    title: 'SERVIÇO DE PREPARAÇÃO DE TERRENO, CULTIVO E COLHEITA',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '0161-0/03',
    title: 'SERVIÇO DE PREPARAÇÃO DE TERRENO, CULTIVO E COLHEITA',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '8599-6/99',
    title: 'OUTRAS ATIVIDADES DE ENSINO NÃO ESPECIFICADAS ANTERIORMENTE',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '8230-0/01',
    title: 'SERVIÇOS DE ORGANIZAÇÃO DE FEIRAS, CONGRESSOS, EXPOSIÇÕES E FESTAS',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '7990-2/00',
    title: 'SERVIÇOS DE RESERVAS E OUTROS SERVIÇOS DE TURISMO NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '7319-0/02',
    title: 'PROMOÇÃO DE VENDAS',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '5590-6/01',
    title: 'ALBERGUES, EXCETO ASSISTENCIAIS',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '5611-2/05',
    title: 'BARES E OUTROS ESTABELECIMENTOS ESPECIALIZADOS EM SERVIR BEBIDAS, COM ENTRETENIMENTO',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '5611-2/04',
    title: 'BARES E OUTROS ESTABELECIMENTOS ESPECIALIZADOS EM SERVIR BEBIDAS, SEM ENTRETENIMENTO',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '5590-6/02',
    title: 'CAMPINGS',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '5620-1/03',
    title: 'CANTINAS - SERVIÇOS DE ALIMENTAÇÃO PRIVATIVOS',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '7319-0/99',
    title: 'OUTRAS ATIVIDADES DE PUBLICIDADE NÃO ESPECIFICADAS ANTERIORMENTE',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '5611-2/03',
    title: 'LANCHONETES, CASAS DE CHÁ, DE SUCOS E SIMILARES',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '5611-2/03',
    title: 'LANCHONETES, CASAS DE CHÁ, DE SUCOS E SIMILARES',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '8230-0/02',
    title: 'CASAS DE FESTAS E EVENTOS',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '5223-1/00',
    title: 'ESTACIONAMENTO DE VEÍCULOS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '9329-8/04',
    title: 'EXPLORAÇÃO DE JOGOS ELETRÔNICOS RECREATIVOS',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '5590-6/99',
    title: 'OUTROS ALOJAMENTOS NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '5611-2/03',
    title: 'LANCHONETES, CASAS DE CHÁ, DE SUCOS E SIMILARES',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '5590-6/03',
    title: 'PENSÕES (ALOJAMENTO)',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '5611-2/01',
    title: 'RESTAURANTES E SIMILARES',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '8299-7/07',
    title: 'SALAS DE ACESSO À INTERNET',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '9329-8/03',
    title: 'EXPLORAÇÃO DE JOGOS DE SINUCA, BILHAR E SIMILARES',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1052-0/00',
    title: 'FABRICAÇÃO DE LATICÍNIOS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4724-5/00',
    title: 'COMÉRCIO VAREJISTA DE HORTIFRUTIGRANJEIROS',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '5612-1/00',
    title: 'SERVIÇOS AMBULANTES DE ALIMENTAÇÃO',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4751-2/02',
    title: 'RECARGA DE CARTUCHOS PARA EQUIPAMENTOS DE INFORMÁTICA',
    nrRisk: 1,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '3839-4/99',
    title: 'RECUPERAÇÃO DE MATERIAIS NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '3831-9/99',
    title: 'RECUPERAÇÃO DE MATERIAIS METÁLICOS, EXCETO ALUMÍNIO',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '3832-7/00',
    title: 'RECUPERAÇÃO DE MATERIAIS PLÁSTICOS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '3831-9/01',
    title: 'RECUPERAÇÃO DE SUCATAS DE ALUMÍNIO',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1353-7/00',
    title: 'FABRICAÇÃO DE ARTEFATOS DE CORDOARIA',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '9529-1/03',
    title: 'REPARAÇÃO DE RELÓGIOS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1359-6/00',
    title: 'FABRICAÇÃO DE OUTROS PRODUTOS TÊXTEIS NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '3313-9/99',
    title: 'MANUTENÇÃO E REPARAÇÃO DE MÁQUINAS, APARELHOS E MATERIAIS ELÉTRICOS NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '9529-1/05',
    title: 'REPARAÇÃO DE ARTIGOS DO MOBILIÁRIO',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '9529-1/99',
    title: 'REPARAÇÃO E MANUTENÇÃO DE OUTROS OBJETOS E EQUIPAMENTOS PESSOAIS E DOMÉSTICOS NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '3314-7/10',
    title: 'MANUTENÇÃO E REPARAÇÃO DE MÁQUINAS E EQUIPAMENTOS PARA USO GERAL NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '3313-9/02',
    title: 'MANUTENÇÃO E REPARAÇÃO DE BATERIAS E ACUMULADORES ELÉTRICOS, EXCETO PARA VEÍCULOS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '9529-1/04',
    title: 'REPARAÇÃO DE BICICLETAS, TRICICLOS E OUTROS VEÍCULOS NÃO MOTORIZADOS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '9529-1/99',
    title: 'REPARAÇÃO E MANUTENÇÃO DE OUTROS OBJETOS E EQUIPAMENTOS PESSOAIS E DOMÉSTICOS NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '3319-8/00',
    title: 'MANUTENÇÃO E REPARAÇÃO DE EQUIPAMENTOS E PRODUTOS NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '3317-1/02',
    title: 'MANUTENÇÃO E REPARAÇÃO DE EMBARCAÇÕES PARA ESPORTE E LAZER',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '9529-1/99',
    title: 'REPARAÇÃO E MANUTENÇÃO DE OUTROS OBJETOS E EQUIPAMENTOS PESSOAIS E DOMÉSTICOS NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '3314-7/02',
    title: 'MANUTENÇÃO E REPARAÇÃO DE EQUIPAMENTOS HIDRÁULICOS E PNEUMÁTICOS, EXCETO VÁLVULAS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '3319-8/00',
    title: 'MANUTENÇÃO E REPARAÇÃO DE EQUIPAMENTOS E PRODUTOS NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '3314-7/10',
    title: 'MANUTENÇÃO E REPARAÇÃO DE MÁQUINAS E EQUIPAMENTOS PARA USO GERAL NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '3314-7/10',
    title: 'MANUTENÇÃO E REPARAÇÃO DE MÁQUINAS E EQUIPAMENTOS PARA USO GERAL NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '3313-9/01',
    title: 'MANUTENÇÃO E REPARAÇÃO DE GERADORES, TRANSFORMADORES E MOTORES ELÉTRICOS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '9529-1/99',
    title: 'REPARAÇÃO E MANUTENÇÃO DE OUTROS OBJETOS E EQUIPAMENTOS PESSOAIS E DOMÉSTICOS NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '9529-1/99',
    title: 'REPARAÇÃO E MANUTENÇÃO DE OUTROS OBJETOS E EQUIPAMENTOS PESSOAIS E DOMÉSTICOS NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '3314-7/09',
    title: 'MANUTENÇÃO E REPARAÇÃO DE MÁQUINAS DE ESCREVER, CALCULAR E DE OUTROS EQUIPAMENTOS NÃO ELETRÔNICOS PARA ESCRITÓRIO',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '3314-7/07',
    title: 'MANUTENÇÃO E REPARAÇÃO DE MÁQUINAS E APARELHOS DE REFRIGERAÇÃO E VENTILAÇÃO PARA USO INDUSTRIAL E COMERCIAL',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '3314-7/99',
    title: 'MANUTENÇÃO E REPARAÇÃO DE OUTRAS MÁQUINAS E EQUIPAMENTOS PARA USOS INDUSTRIAIS NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '3314-7/99',
    title: 'MANUTENÇÃO E REPARAÇÃO DE OUTRAS MÁQUINAS E EQUIPAMENTOS PARA USOS INDUSTRIAIS NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '3314-7/20',
    title: 'MANUTENÇÃO E REPARAÇÃO DE MÁQUINAS E EQUIPAMENTOS PARA A INDÚSTRIA TÊXTIL, DO VESTUÁRIO, DO COURO E CALÇADOS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '3314-7/11',
    title: 'MANUTENÇÃO E REPARAÇÃO DE MÁQUINAS E EQUIPAMENTOS PARA AGRICULTURA E PECUÁRIA',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '3314-7/19',
    title: 'MANUTENÇÃO E REPARAÇÃO DE MÁQUINAS E EQUIPAMENTOS PARA AS INDÚSTRIAS DE ALIMENTOS, BEBIDAS E FUMO',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '3314-7/01',
    title: 'MANUTENÇÃO E REPARAÇÃO DE MÁQUINAS MOTRIZES NÃO ELÉTRICAS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '3314-7/10',
    title: 'MANUTENÇÃO E REPARAÇÃO DE MÁQUINAS E EQUIPAMENTOS PARA USO GERAL NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '3314-7/99',
    title: 'MANUTENÇÃO E REPARAÇÃO DE OUTRAS MÁQUINAS E EQUIPAMENTOS PARA USOS INDUSTRIAIS NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '3314-7/06',
    title: 'MANUTENÇÃO E REPARAÇÃO DE MÁQUINAS, E EQUIPAMENTOS PARA INSTALAÇÕES TÉRMICAS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '9529-1/05',
    title: 'REPARAÇÃO DE ARTIGOS DO MOBILIÁRIO',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '9529-1/99',
    title: 'REPARAÇÃO E MANUTENÇÃO DE OUTROS OBJETOS E EQUIPAMENTOS PESSOAIS E DOMÉSTICOS NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '3311-2/00',
    title: 'MANUTENÇÃO E REPARAÇÃO DE TANQUES, RESERVATÓRIOS METÁLICOS E CALDEIRAS, EXCETO PARA VEÍCULOS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '9529-1/05',
    title: 'REPARAÇÃO DE ARTIGOS DO MOBILIÁRIO',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '3319-8/00',
    title: 'MANUTENÇÃO E REPARAÇÃO DE EQUIPAMENTOS E PRODUTOS NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '3314-7/12',
    title: 'MANUTENÇÃO E REPARAÇÃO DE TRATORES AGRÍCOLAS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '3319-8/00',
    title: 'MANUTENÇÃO E REPARAÇÃO DE EQUIPAMENTOS E PRODUTOS NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '3319-8/00',
    title: 'MANUTENÇÃO E REPARAÇÃO DE EQUIPAMENTOS E PRODUTOS NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '3319-8/00',
    title: 'MANUTENÇÃO E REPARAÇÃO DE EQUIPAMENTOS E PRODUTOS NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '9529-1/99',
    title: 'REPARAÇÃO E MANUTENÇÃO DE OUTROS OBJETOS E EQUIPAMENTOS PESSOAIS E DOMÉSTICOS NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '9002-7/02',
    title: 'RESTAURAÇÃO DE OBRAS DE ARTE',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '2950-6/00',
    title: 'RECONDICIONAMENTO E RECUPERAÇÃO DE MOTORES PARA VEÍCULOS AUTOMOTORES',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '7420-0/03',
    title: 'LABORATÓRIOS FOTOGRÁFICOS',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '5620-1/04',
    title: 'FORNECIMENTO DE ALIMENTOS PREPARADOS PREPONDERANTEMENTE PARA CONSUMO DOMICILIAR',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '0892-4/01',
    title: 'EXTRAÇÃO DE SAL MARINHO',
    nrRisk: 4,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1013-9/01',
    title: 'FABRICAÇÃO DE PRODUTOS DE CARNE',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '9529-1/01',
    title: 'REPARAÇÃO DE CALÇADOS, DE BOLSAS E ARTIGOS DE VIAGEM',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1529-7/00',
    title: 'FABRICAÇÃO DE ARTEFATOS DE COURO NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1813-0/99',
    title: 'IMPRESSÃO DE MATERIAL PARA OUTROS USOS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1813-0/01',
    title: 'IMPRESSÃO DE MATERIAL PARA USO PUBLICITÁRIO',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '2542-0/00',
    title: 'FABRICAÇÃO DE ARTIGOS DE SERRALHERIA, EXCETO ESQUADRIAS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4330-4/05',
    title: 'APLICAÇÃO DE REVESTIMENTOS E DE RESINAS EM INTERIORES E EXTERIORES',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '2539-0/01',
    title: 'SERVIÇOS DE USINAGEM, TORNEARIA E SOLDA',
    nrRisk: 4,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4729-6/99',
    title: 'COMÉRCIO VAREJISTA DE PRODUTOS ALIMENTÍCIOS EM GERAL OU ESPECIALIZADO EM PRODUTOS ALIMENTÍCIOS NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '5612-1/00',
    title: 'SERVIÇOS AMBULANTES DE ALIMENTAÇÃO',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1623-4/00',
    title: 'FABRICAÇÃO DE ARTEFATOS DE TANOARIA E DE EMBALAGENS DE MADEIRA',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1352-9/00',
    title: 'FABRICAÇÃO DE ARTEFATOS DE TAPEÇARIA',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '9609-2/06',
    title: 'SERVIÇOS DE TATUAGEM E COLOCAÇÃO DE PIERCING',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4923-0/01',
    title: 'SERVIÇO DE TÁXI',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1322-7/00',
    title: 'TECELAGEM DE FIOS DE FIBRAS TÊXTEIS NATURAIS, EXCETO ALGODÃO',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1321-9/00',
    title: 'TECELAGEM DE FIOS DE ALGODÃO',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '9001-9/06',
    title: 'ATIVIDADES DE SONORIZAÇÃO E DE ILUMINAÇÃO',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '9511-8/00',
    title: 'REPARAÇÃO E MANUTENÇÃO DE COMPUTADORES E DE EQUIPAMENTOS PERIFÉRICOS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '9521-5/00',
    title: 'REPARAÇÃO E MANUTENÇÃO DE EQUIPAMENTOS ELETROELETRÔNICOS DE USO PESSOAL E DOMÉSTICO',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '9512-6/00',
    title: 'REPARAÇÃO E MANUTENÇÃO DE EQUIPAMENTOS DE COMUNICAÇÃO',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4399-1/99',
    title: 'SERVIÇOS ESPECIALIZADOS PARA CONSTRUÇÃO NÃO ESPECIFICADOS ANTERIORMENTE',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '9601-7/02',
    title: 'TINTURARIAS',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '2539-0/01',
    title: 'SERVIÇOS DE USINAGEM, TORNEARIA E SOLDA',
    nrRisk: 4,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '9609-2/08',
    title: 'HIGIENE E EMBELEZAMENTO DE ANIMAIS DOMÉSTICOS',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '0162-8/02',
    title: 'SERVIÇO DE TOSQUIAMENTO DE OVINOS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '5099-8/01',
    title: 'TRANSPORTE AQUAVIÁRIO PARA PASSEIOS TURÍSTICOS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4924-8/00',
    title: 'TRANSPORTE ESCOLAR',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4930-2/04',
    title: 'TRANSPORTE RODOVIÁRIO DE MUDANÇAS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4929-9/02',
    title: 'TRANSPORTE RODOVIÁRIO COLETIVO DE PASSAGEIROS, SOB REGIME DE FRETAMENTO, INTERMUNICIPAL, INTERESTADUAL E INTERNACIONAL',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '5091-2/02',
    title: 'TRANSPORTE POR NAVEGAÇÃO DE TRAVESSIA, INTERMUNICIPAL, INTERESTADUAL E INTERNACIONAL',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '5011-4/01',
    title: 'TRANSPORTE MARÍTIMO DE CABOTAGEM - CARGA',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4930-2/01',
    title: 'TRANSPORTE RODOVIÁRIO DE CARGA, EXCETO PRODUTOS PERIGOSOS E MUDANÇAS, MUNICIPAL',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4929-9/01',
    title: 'TRANSPORTE RODOVIÁRIO COLETIVO DE PASSAGEIROS, SOB REGIME DE FRETAMENTO, MUNICIPAL',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '5091-2/01',
    title: 'TRANSPORTE POR NAVEGAÇÃO DE TRAVESSIA, MUNICIPAL',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '5021-1/01',
    title: 'TRANSPORTE POR NAVEGAÇÃO INTERIOR DE CARGA, MUNICIPAL, EXCETO TRAVESSIA',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1422-3/00',
    title: 'FABRICAÇÃO DE ARTIGOS DO VESTUÁRIO, PRODUZIDOS EM MALHARIAS E TRICOTAGENS, EXCETO MEIAS',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '3291-4/00',
    title: 'FABRICAÇÃO DE ESCOVAS, PINCÉIS E VASSOURAS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '5612-1/00',
    title: 'SERVIÇOS AMBULANTES DE ALIMENTAÇÃO',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4724-5/00',
    title: 'COMÉRCIO VAREJISTA DE HORTIFRUTIGRANJEIROS',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4724-5/00',
    title: 'COMÉRCIO VAREJISTA DE HORTIFRUTIGRANJEIROS',
    nrRisk: 2,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4520-0/01',
    title: 'SERVIÇOS DE MANUTENÇÃO E REPARAÇÃO MECÂNICA DE VEÍCULOS AUTOMOTORES',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4330-4/99',
    title: 'OUTRAS OBRAS DE ACABAMENTO DA CONSTRUÇÃO',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '1099-6/01',
    title: 'FABRICAÇÃO DE VINAGRES',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '0121-1/01',
    title: 'HORTICULTURA, EXCETO MORANGO',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4930-2/01',
    title: 'TRANSPORTE RODOVIÁRIO DE CARGA MUNICIPAL, EXCETO PRODUTOS PERIGOSOS, MUDANÇAS, INTERMUNICIPAL, INTERESTADUAL E INTERNACIONAL',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4930-2/02',
    title: 'TRANSPORTE RODOVIÁRIO DE CARGA INTERMUNICIPAL, INTERESTADUAL E INTERNACIONAL, EXCETO PRODUTOS PERIGOSOS E MUDANÇAS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4930-2/03',
    title: 'TRANSPORTE RODOVIÁRIO DE PRODUTOS PERIGOSOS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
  {
    code: '4930-2/04',
    title: 'TRANSPORTE RODOVIÁRIO DE MUDANÇAS',
    nrRisk: 3,
    source: 'Anexo XI - Resolução CGSN nº 140/2018 (MEI)',
  },
];

async function seedCNAE() {
  console.log('✨ Upserting CNAEs (grau de risco)...');

  for (const item of CNAE_SEED) {
    await prisma.cNAE.upsert({
      where: { code: item.code },
      update: {
        title: item.title,
        nrRisk: item.nrRisk,
        source: item.source,
      },
      create: {
        code: item.code,
        title: item.title,
        nrRisk: item.nrRisk,
        source: item.source,
      },
    });
  }

  console.log(`✅ ${CNAE_SEED.length} CNAEs atualizados/criados.`);
}

async function main() {
  try {
    await seedCNAE();
  } catch (error) {
    console.error('❌ Seed de CNAE falhou:', error);
    process.exit(1);
  } finally {
    await prisma.$disconnect();
  }
}

main();